auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Joker's Blog”
title: Joker's blog
description: Everything about Joker.
url: http://xgiton.github.io
feed: /atom.xml
author_info: <a href="http://xgiton.github.io/">Joker</a>
